#pragma once
#ifndef MAX
#define MAX(a, b) (a) > (b) ? (a) : (b)
#endif
#ifndef MIN
#define MIN(a, b) (a) < (b) ? (a) : (b)
#endif

#ifndef COORD_UNIT_MM
#define COORD_UNIT_MM	0
#endif

#ifndef COORD_UNIT_CM
#define COORD_UNIT_CM	1
#endif

#ifndef COORD_UNIT_M
#define COORD_UNIT_M	2
#endif

#ifndef COORD_UNIT_ENUM
#define COORD_UNIT_ENUM	"mm|cm|m"
#endif

enum SVM_MODE { TRAINING, PREDICTION };

#ifndef MAX_INPUT_NUMBER
#define MAX_INPUT_NUMBER 10
#endif

#ifndef MAXIMUM_2D_POINT_NUMBER
#define MAXIMUM_2D_POINT_NUMBER 3000
#endif
#ifndef MAXIMUM_3D_POINT_NUMBER
#define MAXIMUM_3D_POINT_NUMBER 150000
#endif
#ifndef MAXIMUM_SEGMENT_NUMBER
#define MAXIMUM_SEGMENT_NUMBER 1000
#endif
#ifndef MAXIMUM_OBJECT_NUMBER
#define MAXIMUM_OBJECT_NUMBER 100
#endif
#ifndef MAXIMUM_LASER_OBJECT_NUMBER
#define MAXIMUM_LASER_OBJECT_NUMBER 1000
#endif
#ifndef MAXIMUM_NAME_SIZE
#define MAXIMUM_NAME_SIZE 15
#endif
#ifndef MAXIMUM_NB_LEGEND
#define MAXIMUM_NB_LEGEND 10
#endif

#ifndef INPUT_POINT
#define INPUT_POINT 0
#endif
#ifndef INPUT_SEGMENT
#define INPUT_SEGMENT 1
#endif
#ifndef INPUT_OBJECT
#define INPUT_OBJECT 2
#endif
#ifndef INPUT_LASER_OBJECT
#define INPUT_LASER_OBJECT 3
#endif
#ifndef INPUT_IMARA_OBJECT
#define INPUT_IMARA_OBJECT 4
#endif
#ifndef INPUT_IMAGE
#define INPUT_IMAGE 5
#endif
#ifndef INPUT_GEOAREAS
#define INPUT_GEOAREAS 6
#endif

#ifndef DRAWING_CIRCLE
#define DRAWING_CIRCLE 0
#endif

#ifndef DRAWING_RECTANGLE
#define DRAWING_RECTANGLE 1
#endif

#ifndef DRAWING_COVARIANCE_ELLIPSE
#define DRAWING_COVARIANCE_ELLIPSE 2
#endif

#ifndef DRAWING_TRIANGLE
#define DRAWING_TRIANGLE 3
#endif

#ifndef DRAWING_SQUARE
#define DRAWING_SQUARE 4
#endif

#ifndef DRAWING_CROSS
#define DRAWING_CROSS 5
#endif

#ifndef COORDINATES_VEHICLE
#define COORDINATES_VEHICLE 0
#endif

#ifndef COORDINATES_GLOBAL
#define COORDINATES_GLOBAL 1
#endif

#ifndef DETECTION_2D
#define DETECTION_2D 0
#endif

#ifndef DETECTION_3D
#define DETECTION_3D 1
#endif

#ifndef NO_CLASSIFICATION
#define NO_CLASSIFICATION 0
#endif

#ifndef CLASSIFICATION_LOVE_ALLOBJECTS
#define CLASSIFICATION_LOVE_ALLOBJECTS 1
#endif

#ifndef CLASSIFICATION_LOVE_PEDESTRIANS
#define CLASSIFICATION_LOVE_PEDESTRIANS 2
#endif

#ifndef CLASSIFICATION_LOVE_GROUPPEDESTRIANS
#define CLASSIFICATION_LOVE_GROUPPEDESTRIANS 3
#endif

#ifndef CLASSIFICATION_MULTICLASS
#define CLASSIFICATION_MULTICLASS 4
#endif

#ifndef NO_TRACKING
#define NO_TRACKING 0
#endif

#ifndef TRACKING_KALMAN_JPDAF
#define TRACKING_KALMAN_JPDAF 1
#endif

#ifndef PI
#define PI 3.141592653589793238462 
#endif

#ifndef NO_TEXT
#define NO_TEXT 0
#endif

#ifndef TEXT_POSITION
#define TEXT_POSITION 1
#endif

#ifndef TEXT_VELOCITY
#define TEXT_VELOCITY 2
#endif

#ifndef TEXT_NOTE
#define TEXT_NOTE 3
#endif

#ifndef TEXT_ID
#define TEXT_ID 4
#endif

#ifndef NO_PROJECTION
#define NO_PROJECTION 0
#endif

#ifndef PROJECTION_POSITION
#define PROJECTION_POSITION 1
#endif

#ifndef PROJECTION_PIXEL
#define PROJECTION_PIXEL 2
#endif

#ifndef ASSESSMENT_LOVE
#define ASSESSMENT_LOVE 0
#endif

#ifndef ASSESSMENT_PATH
#define ASSESSMENT_PATH 1
#endif

#ifndef CAMERA_CLASSIFICATION_CASCADE
#define CAMERA_CLASSIFICATION_CASCADE 0
#endif

#ifndef CAMERA_CLASSIFICATION_HOG
#define CAMERA_CLASSIFICATION_HOG 1
#endif

#ifndef CAMERA_CLASSIFICATION_FULLIMAGE
#define CAMERA_CLASSIFICATION_FULLIMAGE 0
#endif

#ifndef CAMERA_CLASSIFICATION_SUBWINDOWS
#define CAMERA_CLASSIFICATION_SUBWINDOWS 1
#endif

#ifndef CAMERA_CLASSIFICATION_INPUT_LASER
#define CAMERA_CLASSIFICATION_INPUT_LASER 2
#endif

#ifndef CAMERA_CLASSIFICATION_SERIAL_LASER
#define CAMERA_CLASSIFICATION_SERIAL_LASER 3
#endif

#ifndef CAMERA_CLASSIFICATION_SERIAL_OBJECTS
#define CAMERA_CLASSIFICATION_SERIAL_OBJECTS 4
#endif

#ifndef CAMERA_CLASSIFICATION_SERIAL_IMARA_OBJECTS
#define CAMERA_CLASSIFICATION_SERIAL_IMARA_OBJECTS 5
#endif

#ifndef NO_FUSION
#define NO_FUSION 0
#endif

#ifndef FUSION_PARALLEL
#define FUSION_PARALLEL 1
#endif

#ifndef FUSION_SERIAL
#define FUSION_SERIAL 2
#endif

#ifndef FUSION_PARALLEL_TRACKS
#define FUSION_PARALLEL_TRACKS 3
#endif

#ifndef FUSION_SERIAL_TRACKS
#define FUSION_SERIAL_TRACKS 4
#endif

#ifndef FUSION_INPUT_OBJECT
#define FUSION_INPUT_OBJECT 0
#endif

#ifndef FUSION_INPUT_LASER_OBJECT
#define FUSION_INPUT_LASER_OBJECT 1
#endif

#ifndef FUSION_OUTPUT_FUSED
#define FUSION_OUTPUT_FUSED 0
#endif

#ifndef FUSION_OUTPUT_LASER_ALONE
#define FUSION_OUTPUT_LASER_ALONE 1
#endif

#ifndef FUSION_OUTPUT_VISION_ALONE
#define FUSION_OUTPUT_VISION_ALONE 2
#endif

#ifndef FUSION_OUTPUT_ALL
#define FUSION_OUTPUT_ALL 3
#endif

#ifndef FUSION_OUTPUT_CLASS
#define FUSION_OUTPUT_CLASS 4
#endif

#ifndef V2P_INPUT_VEHICLESTATE
#define V2P_INPUT_VEHICLESTATE 0
#endif
#ifndef V2P_INPUT_PACKET
#define V2P_INPUT_PACKET 1
#endif
#ifndef V2P_INPUT_TRIGGER
#define V2P_INPUT_TRIGGER 2
#endif

#ifndef NB_EDGES
#define NB_EDGES 4
#endif

#ifndef NB_LASER_FEATURES
#define NB_LASER_FEATURES 80
#endif

#ifndef NB_CLASSES
#define NB_CLASSES 3
#endif

#ifndef CLASS_NO_OBJECT
#define CLASS_NO_OBJECT 0
#endif

#ifndef CLASS_PEDESTRIAN
#define CLASS_PEDESTRIAN 1
#endif

#ifndef CLASS_VEHICLE
#define CLASS_VEHICLE 2
#endif

#ifndef LEGEND_POINT
#define LEGEND_POINT 0
#endif

#ifndef LEGEND_CIRCLE
#define LEGEND_CIRCLE 1
#endif

#ifndef LEGEND_RECTANGLE
#define LEGEND_RECTANGLE 2
#endif

#ifndef V2PFUSION_OUTPUT_FUSED
#define V2PFUSION_OUTPUT_FUSED 0
#endif

#ifndef V2PFUSION_OUTPUT_ASS
#define V2PFUSION_OUTPUT_ASS 1
#endif

#ifndef V2PFUSION_OUTPUT_NP
#define V2PFUSION_OUTPUT_NP 2
#endif

#ifndef V2PFUSION_OUTPUT_NC
#define V2PFUSION_OUTPUT_NC 3
#endif

#ifndef V2PFUSION_OUTPUT_GATE
#define V2PFUSION_OUTPUT_GATE 4
#endif

#ifndef V2PFUSION_MAXIMUM_DISTANCE
#define V2PFUSION_MAXIMUM_DISTANCE 1000
#endif